/*This file has been prepared for Doxygen automatic documentation generation.*/
/*! \file *********************************************************************
 *
 * \brief Timer 
 *
 * Discrete PID controller implementation. Set up by giving P/I/D terms
 * to Init_PID(), and uses a struct PID_DATA to store internal values.
 *
 * - File:               timer.c
 * - Compiler:           AGCC
 * - Supported devices:  All AVR devices
 *
 * \author               Stephan Harms
 *                       Support email: avr@stephanharms.de
 *
 * $Name$
 * $Revision: 1 $
 * $RCSfile$
 * $Date: 2009-03-02$
 *****************************************************************************/

#include "timer.h"


#include <avr/io.h>
#include <avr/interrupt.h>

// the values are calculated with AvrWiz for ATmega8 @ 16 mhz
// Timer0 settings: 159744 ticks (= 9.984 ms)

// Timer0 Overflow
ISR(TIMER0_OVF_vect)
{
	// reinit counter
	TCNT0 = 100;
}

void Timer0_init()
{
	// Timer0 settings: ~ 159744 ticks (9.984 ms)
	TCCR0 = (1<<CS02) | (1<<CS00); // prescaler = 1024
	// init counter
	TCNT0 = 100;
	TIMSK = (1<<TOIE0); // Timer0 Overflow Interrupt Enable
}

void init_timer()
{
	Timer0_init();
}



// generated by AvrWiz on 3/3/2009 8:27:54 PM

